### ISSUE TITLE
Additional dependency

### ISSUE THREAD

**Issue by bgagl** [LeoVarnet/AM_FM_Spectra#1]
Hi there, 

thanks for sharing this code. I just noticed that one dependency is missing. For the isyes function, your MFB_Model package has to be in the path as well. 

Also, I am not sure if my RAM is sufficient. Can you estimate how much RAM is needed for a 100mb wav file? Or is it optimized for smaller files?

Best wishes, 
Benjamin

**Comment by bgagl** [comment]
Now that I found out that it is not practical to run the script with long files another issue occurred. 

```
>> run Script_modulation_spectra_.m

processing stim 1 of 1
sound loading
E/FM extraction
calculating envelope spectra
calculating Nth octave-band spectra
calculating FM spectra
f0 extraction
calculating f0 modulation spectrum
Undefined function 'plomb' for input arguments of type 'double'.

Error in Script_modulation_spectra_ (line 174)
    [f0_P,f_periodo] = plomb(f0withoutnan,twithoutnan,100,16);

Error in run (line 64)
evalin('caller', [script ';']);

```
would be really great if you could point out what the problem is here.

Thanks in advance, 
Benjamin

**Comment by LeoVarnet** [comment]
Thanks for your comments Benjamin!
I just added the missing isyes function
The script is not optimized for long audio files (I never used it on .wav longer than 10s). I'm afraid that the YIN algorithm and Hilbert extraction will be very time consuming when ran on long signals...

**Comment by LeoVarnet** [comment]
For your second comment I guess you're not using MATLAB's signal processing toolbox, which includes the plomb function. In that case you can uncomment the next line and use the fastlomb function instead (https://uk.mathworks.com/matlabcentral/fileexchange/22215-lomb-normalized-periodogram).

**Comment by bgagl** [comment]
Hm, unfortunately, I get a very similar error message when using `fastlomb`.

```
>> run Script_modulation_spectra_.m

processing stim 1 of 1
sound loading
E/FM extraction
calculating envelope spectra
calculating Nth octave-band spectra
calculating FM spectra
f0 extraction
calculating f0 modulation spectrum
Undefined function 'fastlomb' for input arguments of type 'double'.

Error in Script_modulation_spectra_ (line 173)
    [f0_P,f_periodo] = fastlomb(f0withoutnan,twithoutnan,0,1,20); f0_P =
    sqrt(f0_P/length(twithoutnan));

Error in run (line 64)
evalin('caller', [script ';']);

```

and so far as I see I am using the signal processing toolbox

**Comment by LeoVarnet** [comment]
Ok then maybe you should check the content of this 'script' variable in run...? https://stackoverflow.com/questions/38600125/command-line-matlab-script-calls-give-undefined-variable-class-errors
Weird that I never get this error message before though

**Comment by bgagl** [comment]
Hi Leo, 

I could not identify the issue so I commented out the section on the f0 estimation for now. 

Still I managed to get my first results for the AM spectra (I expect this is the parameter which was described as AMa spectrum in the paper) and the Modulation index sprectra (AMi spectrum in the paper) for one 6 second speech file. See the result below.

![grafik](https://user-images.githubusercontent.com/31654516/48693034-67b24600-ebd8-11e8-8838-0c53be00b2d6.png)

and here for a second 6 second snipped

![grafik](https://user-images.githubusercontent.com/31654516/48695520-a5ff3380-ebdf-11e8-813d-76c20432cfdb.png)

are these reasonable results?

One other thing. Is there a way to increase the speed for the hilbert extracter ... currently it takes about 40 min for a 6s snip. 

Thanks in advance.

**Comment by lvarnet** [comment]
Ok first there is something weird with these spectra indeed. Are you using the latest version of the script? Would you mind checking if E is a number_of_channels X number_of_samples matrix?
You can't speed up the hilbert extraction itself but depending of you goal you can adapt several parts of the script: if you're interested only in the AM you can replace the hilbert extraction with a simpler envelope extraction function. Alternatively you can reduce the number of gammatone channels (in some papers the AM spectrum is calculated only in the band centered on 1 kHz)

**Comment by lvarnet** [comment]
Wow I misread the part about the computation time... 40 min is way too long for a 6 s sound ! But maybe this is related to the issue above. If you want to send me a sample of sound you use I can run the script on my computer and we'll see what happens.

**Comment by bgagl** [comment]
Ok, the size of E is 30 (Channels) X 176401 (number of samples) for a 4 s snip. I ran this with the latest version of the code, and it was faster as expected. 

My primary interest is the modulation spectrum parameter which I want to estimate for a couple of participants as a measure of individual differences. Does this make sense to you?

**Comment by bgagl** [comment]
![grafik](https://user-images.githubusercontent.com/31654516/48827895-a7ab3180-ed6e-11e8-9009-080038b39fd5.png)
![grafik](https://user-images.githubusercontent.com/31654516/48828061-12f50380-ed6f-11e8-8b17-6522d04b8a08.png)

here is also the graphical output for a 4s snip and a 6s snip ... looks much better to me 
speed is also up ... current estimation time is ~1 min

Thanks for your time on this. One more thing, could you recommend a snip length or range that would be reasonable?

**Comment by lvarnet** [comment]
It looks much better indeed ! 
The length T of the audio file to use depends primarily on the lowest rate you're interested in (the modulation amplitude at rate 1/T being estimated on 1 single cycle). That's the only recommendation for the AM.

**Comment by lvarnet** [comment]
So if you're interested e.g. in the interindividual variability in the main peak of the AMi spectrum (reflecting the speaker's articulation rate, around 3/4 Hz) a 4s snip is more than sufficient

**Comment by bgagl** [comment]
Cool, thanks once more for helping out and sharing.
